USE [master]
GO

/****** Object:  Database [waste-management]    Script Date: 19/05/2017 10:05:25 AM ******/
CREATE DATABASE [waste-management]
GO

ALTER DATABASE [waste-management] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [waste-management].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [waste-management] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [waste-management] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [waste-management] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [waste-management] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [waste-management] SET ARITHABORT OFF 
GO

ALTER DATABASE [waste-management] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [waste-management] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [waste-management] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [waste-management] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [waste-management] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [waste-management] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [waste-management] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [waste-management] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [waste-management] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [waste-management] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [waste-management] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [waste-management] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [waste-management] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [waste-management] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [waste-management] SET  MULTI_USER 
GO

ALTER DATABASE [waste-management] SET DB_CHAINING OFF 
GO

ALTER DATABASE [waste-management] SET ENCRYPTION ON
GO

ALTER DATABASE [waste-management] SET QUERY_STORE = ON
GO

ALTER DATABASE [waste-management] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO

ALTER DATABASE [waste-management] SET  READ_WRITE 
GO


